
#include "roundingsat.hpp"
namespace licenses {
const char* roundingsat =
    "Copyright (c) 2014-2020, Jan Elffers\n"
    "Copyright (c) 2019-2021, Jo Devriendt\n"
    "Copyright (c) 2020-2021, Stephan Gocht\n"
    "Copyright (c) 2014-2021, Jakob Nordström\n"
    "\n"
    "Parts of the code were copied or adapted from MiniSAT.\n"
    "\n"
    "MiniSAT -- Copyright (c) 2003-2006, Niklas Een, Niklas Sorensson\n"
    "           Copyright (c) 2007-2010  Niklas Sorensson\n"
    "\n"
    "Permission is hereby granted, free of charge, to any person obtaining a\n"
    "copy of this software and associated documentation files (the\n"
    "\"Software\"), to deal in the Software without restriction, including\n"
    "without limitation the rights to use, copy, modify, merge, publish,\n"
    "distribute, sublicense, and/or sell copies of the Software, and to\n"
    "permit persons to whom the Software is furnished to do so, subject to\n"
    "the following conditions:\n"
    "\n"
    "The above copyright notice and this permission notice shall be included\n"
    "in all copies or substantial portions of the Software.\n"
    "\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS\n"
    "OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n"
    "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\n"
    "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\n"
    "LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\n"
    "OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION\n"
    "WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n";
}
