
#include "zib_academic.hpp"
namespace licenses {
const char* zib_academic =
    "ZIB ACADEMIC LICENSE\n"
    "\n"
    "This license for ZIB software is designed to guarantee freedom to share and\n"
    "change software for academic use, but restricting commercial firms\n"
    "from exploiting your knowhow for their benefit. The precise terms and\n"
    "conditions for using, copying, distribution, and modification follow.\n"
    "\n"
    "\n"
    "\n"
    "Terms and Conditions for Using, Copying, Distribution, and Modification\n"
    "\n"
    "The \"Program\" below refers to source, object and executable code, and a\n"
    "\"work based on the Program\" means either the Program or any\n"
    "derivative work under copyright law: that is a work containing the Program\n"
    "or a portion of it, either verbatim or with modifications and/or translated\n"
    "into another language. Each licensee is addressed as \"you\".\n"
    "\n"
    "1. This license applies to you only if you are a member of a noncommercial\n"
    "   and academic institution, e.g., a university. The license expires as\n"
    "   soon as you are no longer a member of this institution.\n"
    "2. Every publication and presentation for which work based on the Program\n"
    "   or its output has been used must contain an appropriate citation\n"
    "   and aknowledgement of the author(s) of the Program.\n"
    "3. You may copy and distribute the Program or work based on the Program\n"
    "   in source, object, or executable form provided that you also meet\n"
    "   all of the following conditions:\n"
    "\n"
    "   a. You must cause any work that you distribute or publish, that in whole\n"
    "      or in part contains or is derived from the Program or any\n"
    "      part thereof, to be licensed as a whole at no charge under the terms of\n"
    "      this License. You must accompany it with this unmodified license text.\n"
    "\n"
    "      These requirements apply to the Program or work based on the Program\n"
    "      as a whole. If identifiable sections of that work are\n"
    "      not derived from the Program, and can be reasonably considered\n"
    "      independent and separate works in themselves, this License\n"
    "      does not apply to those sections when you distribute them as\n"
    "      separate works. But when you distribute the same sections as\n"
    "      part of a whole which is a work based on the Program, the distribution\n"
    "      of the whole must be on the terms of this License,\n"
    "      whose permissions for other licensees extend to the entire whole and,\n"
    "      thus, to each and every part regardless of who wrote it.\n"
    "\n"
    "   b. You must cause the modified files to carry prominent notices stating\n"
    "      that you changed the files and the date of any change.\n"
    "   c. You must keep track of access to the Program (e.g., similar to the\n"
    "      registration procedure at ZIB).\n"
    "   d. You must accompany it with the complete corresponding machine-readable\n"
    "      source code.\n"
    "\n"
    "      The source code for a work means the preferred form of the work for\n"
    "      making modifications to it. For an executable work,\n"
    "      complete source code means all the source code for all modules it\n"
    "      contains, plus any associated interface definition files, plus\n"
    "      the scripts used to control compilation and installation of the\n"
    "      executable. However, as a special exception, the source code\n"
    "      distributed need not include anything that is normally distributed\n"
    "      (in either source or binary form) with the major components\n"
    "      (compiler, kernel, and so on) of the operating system on which the\n"
    "      executable runs, unless that component itself accompanies\n"
    "      the executable.\n"
    "\n"
    "4. You may not copy, modify, sublicense, or distribute the Program except as\n"
    "   expressly provided under this License. Any attempt otherwise to\n"
    "   copy, modify, sublicense, or distribute the Program is void and will\n"
    "   automatically terminate your rights under this License. However, parties\n"
    "   who have received copies or rights from you under this License will\n"
    "   not have their licenses terminated so long as such parties remain in full\n"
    "   compliance.\n"
    "5. You are not required to accept this License, since you have not signed it.\n"
    "   However, nothing else grants you permission to use, modify, or\n"
    "   distribute the Program or its derivative works. These actions are\n"
    "   prohibited by law if you do not accept this License. Therefore, by using,\n"
    "   modifying or distributing the Program (or any work based on the Program),\n"
    "   you indicate your acceptance of this License to do so and all its\n"
    "   terms and conditions for copying, distributing or modifying the Program\n"
    "   or works based on it.\n"
    "6. Each time you redistribute the Program (or any work based on the Program),\n"
    "   the recipient automatically receives a license from the original\n"
    "   licensor to copy, distribute or modify the Program subject to these terms\n"
    "   and conditions. You may not impose any further restrictions on the\n"
    "   recipient's exercise of the rights granted herein. You are not responsible\n"
    "   for enforcing compliance by third parties to this License.\n"
    "7. If, as a consequence of a court judgment or allegation of patent\n"
    "   infringement or for any other reason (not limited to patent issues),\n"
    "   conditions are imposed on you (whether by court order, agreement, or\n"
    "   otherwise) that contradict the conditions of this License, they do not\n"
    "   excuse you from the conditions of this License.\n"
    "8. If you wish to incorporate parts of the Program into other programs whose\n"
    "   distribution conditions are different, write to ZIB to ask for permission.\n"
    "\n"
    "NO WARRANTY\n"
    "\n"
    "9. Because the program is licensed free of charge, there is no warranty for\n"
    "   the program to the extent permitted by applicable law. The\n"
    "   copyright holders provide the program \"as is\" without warranty of any\n"
    "   kind, either expressed or implied, including, but not limited to, the\n"
    "   implied warranties of merchantability and fitness for a particular purpose.\n"
    "   The entire risk as to the quality and performance of the program is\n"
    "   with you. Should the program prove defective, you assume the cost of all\n"
    "   necessary servicing, repair, or correction.\n"
    "10.In no event will any copyright holder, or any other party who may modify\n"
    "   and/or redistribute the program as permitted above, be liable to\n"
    "   you for damages, including any general, special, incidental or\n"
    "   consequential damages arising out of the use or inability to use the\n"
    "   program (including but not limited to loss of data or data being rendered\n"
    "   inaccurate or losses sustained by you or third parties or a failure of the\n"
    "   program to operate with any other programs), even if such holder or other\n"
    "   party has been advised of the possibility of such damages.\n";
}
